version: '3.8'
services:
  umubyeyi:
    image: umubyeyi-backend
    ports:
      - "9009:8181"
    depends_on:
      - db
    networks:
      - umubyeyibackend-net
    restart: always

  db:
    image: mysql
    environment:
      # MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_DATABASE: $DB_DATABASE
      # MYSQL_USER: $DB_USERNAME
      # MYSQL_PASSWORD: $DB_PASSWORD
    # volumes:
    #   - dbdata_umubyeyi:/var/lib/mysql
      # - ./data/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks: 
      - umubyeyibackend-net

networks: 
  umubyeyibackend-net:
    external: false

# volumes:
#   dbdata_umubyeyi:
#      external: true

# volumes:
#   mysql_data: { driver: local }